name: ServerGate
version: ${project.version}
main: plugin.midorin.info.sg.ServerGatePlugins

commands:
  servergate:
    description: ServerGateのメインコマンドです。
    aliases:
      - sg
      - gate
  nick:
    description: 自分のニックネームを変更するコマンドです。